"""Code generation — render recorded flow nodes as a replayable bot script.

Desktop equivalent of Playwright's codegen output: takes the ``nodes``
written by any capture mode (``single`` is just a one-node flow) and
emits a :class:`Smithy` bot that replays them.

Honesty rules (same spirit as selector ranking — no made-up stability):

* the recorder never sees the launched process, so the script starts
  with a ``TODO`` showing how to add ``process_run`` + PID scoping;
* series-mode ``input_text`` nodes carry no ``text`` (only the fact that
  keys were pressed) — the emitter writes an explicit
  ``\"TODO: fill in\"`` placeholder instead of silently typing nothing;
* static selector-fragility hints from
  :func:`stability_penalty` are emitted as ``WARNING`` comments.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from typing import Any

from smithy.core.errors import InvalidInput
from smithy.windows.selector_rank import stability_penalty

_TOOL_METHOD = {
    "windows.click": "click",
    "windows.input_text": "input_text",
    "windows.set_text": "set_text",
    "windows.wait": "wait",
}

_TEXT_PLACEHOLDER = "TODO: fill in"


def emit_bot(nodes: Sequence[Mapping[str, Any]], *, source: str = "flow.json") -> str:
    """Render *nodes* as a replayable ``Smithy`` bot script.

    Args:
        nodes: Flow nodes (``{\"tool\", \"args\"}`` mappings) as written by
            any capture mode.
        source: Name of the capture file, referenced in the header.

    Returns:
        The complete Python source of the bot.

    Raises:
        InvalidInput: If a node names an unknown tool.
    """
    lines = [
        f'"""Replay script generated by smithy codegen from {source!r}.',
        "",
        "Review before running: fill in TODOs (app launch, typed text) and",
        "check WARNING comments on fragile selectors.",
        '"""',
        "",
        "import asyncio",
        "",
        "from smithy import Smithy",
        "from smithy.windows.tools import windows_tools",
        "",
        "bot = Smithy(tools=windows_tools())",
        "",
        "",
        "async def main() -> None:",
        "    # TODO: launch the app and scope the bot to it, e.g.",
        '    #   app = await bot.process_run("notepad.exe")',
        "    #   await bot.click(app, ...)",
    ]
    if not nodes:
        lines.append("    pass")
    for node in nodes:
        lines.extend(_emit_node(node))
    lines.extend(
        [
            "",
            "",
            'if __name__ == "__main__":',
            "    asyncio.run(main())",
            "",
        ]
    )
    return "\n".join(lines)


def emit_file(input_path: str, output_path: str) -> str:
    """Read a capture file and write the generated bot script.

    Args:
        input_path: Path to a capture JSON file with a ``nodes`` list.
        output_path: Path to write the generated ``.py`` script to.

    Returns:
        The generated source (also written to *output_path*).

    Raises:
        InvalidInput: If the file has no ``nodes`` list or a node names
            an unknown tool.
    """
    with open(input_path, encoding="utf-8") as fh:
        data = json.load(fh)
    nodes = data.get("nodes") if isinstance(data, dict) else None
    if not isinstance(nodes, list):
        raise InvalidInput(
            f"Capture file {input_path!r} has no 'nodes' list",
            param="nodes",
            input_value=input_path,
        )
    source = emit_bot(nodes, source=input_path)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(source)
    return source


def _emit_node(node: Mapping[str, Any]) -> list[str]:
    """Render one flow node as commented ``await bot.*(...)`` lines."""
    tool = node.get("tool")
    method = _TOOL_METHOD.get(tool) if isinstance(tool, str) else None
    if method is None:
        raise InvalidInput(
            f"Cannot emit code for tool {tool!r}",
            param="tool",
            input_value=tool,
        )
    raw_args = node.get("args")
    args: dict[str, Any] = dict(raw_args) if isinstance(raw_args, Mapping) else {}

    lines: list[str] = []
    if method in ("click", "input_text", "set_text"):
        for warning in _selector_warnings(args):
            lines.append(f"    # WARNING: {warning}")
    if method in ("input_text", "set_text") and not args.get("text"):
        lines.append("    # TODO: recorder did not capture the typed text — fill in")
        args["text"] = _TEXT_PLACEHOLDER
    kwargs = ",\n".join(f"        {key}={value!r}" for key, value in args.items())
    if kwargs:
        lines.append(f"    await bot.{method}(\n{kwargs},\n    )")
    else:
        lines.append(f"    await bot.{method}()")
    return lines


_SELECTOR_KEYS = ("name", "automation_id", "control_type", "class_name")


def _selector_warnings(args: Mapping[str, Any]) -> tuple[str, ...]:
    """Return static fragility hints for selector *args* (never raises).

    Only selector fields are inspected — the typed ``text`` value is not
    a selector and would otherwise trigger false "dynamic name" warnings.
    """
    selector_args = {k: v for k, v in args.items() if k in _SELECTOR_KEYS and isinstance(v, str)}
    try:
        _, warnings = stability_penalty(selector_args)
    except Exception:
        return ()
    return warnings
