"""Replay script generated by smithy codegen from 'flow.json'.

Review before running: fill in TODOs (app launch, typed text) and
check WARNING comments on fragile selectors.
"""

import asyncio

from smithy import Smithy
from smithy.windows.tools import windows_tools

bot = Smithy(tools=windows_tools())


async def main() -> None:
    # TODO: launch the app and scope the bot to it, e.g.
    #   app = await bot.process_run("notepad.exe")
    #   await bot.click(app, ...)
    await bot.click(
        name='Файл',
        control_type='menuitem',
    )
    # WARNING: name 'python -m smithy.windows.tools.selector_capture record -o flow.json --emit bot.…' is long — brittle if the text shifts
    await bot.click(
        name='python -m smithy.windows.tools.selector_capture record -o flow.json --emit bot.…',
        control_type='pane',
    )


if __name__ == "__main__":
    asyncio.run(main())
