"""Tests for selector_capture codegen — nodes to replayable bot script.

Pure rendering tests (no UIA): the emitter only reads node dicts.
"""

from __future__ import annotations

import json
from typing import Any
from unittest.mock import patch

import pytest

from smithcore.core.errors import InvalidInput
from smithcore.windows.tools.selector_capture.emit import emit_bot, emit_file


def _click(**kwargs: Any) -> dict[str, Any]:
    return {"tool": "windows.click", "args": dict(kwargs)}


class TestEmitBot:
    def test_header_and_footer(self) -> None:
        src = emit_bot([], source="flow.json")
        assert "generated by smithcore codegen from 'flow.json'" in src
        assert "from smithcore import SmithCore" in src
        assert "from smithcore.windows.tools import windows_tools" in src
        assert "bot = SmithCore(tools=windows_tools())" in src
        assert "async def main() -> None:" in src
        assert "process_run" in src
        assert 'if __name__ == "__main__":' in src
        assert "asyncio.run(main())" in src

    def test_empty_nodes_emit_pass(self) -> None:
        assert "\n    pass\n" in emit_bot([])

    def test_click_kwargs(self) -> None:
        src = emit_bot([_click(name="Формат", control_type="menuitem")])
        assert "await bot.click(" in src
        assert "name='Формат'" in src
        assert "control_type='menuitem'" in src

    def test_input_text_with_text(self) -> None:
        src = emit_bot([{"tool": "windows.input_text", "args": {"name": "Field", "text": "hi"}}])
        assert "await bot.input_text(" in src
        assert "text='hi'" in src
        assert "TODO: fill in" not in src

    def test_input_text_without_text_gets_placeholder(self) -> None:
        src = emit_bot([{"tool": "windows.input_text", "args": {"name": "Field"}}])
        assert "TODO" in src
        assert "text='TODO: fill in'" in src

    def test_set_text_without_text_gets_placeholder(self) -> None:
        src = emit_bot([{"tool": "windows.set_text", "args": {"name": "Field"}}])
        assert "await bot.set_text(" in src
        assert "text='TODO: fill in'" in src

    def test_wait_timeout(self) -> None:
        src = emit_bot([{"tool": "windows.wait", "args": {"timeout_ms": 2000}}])
        assert "await bot.wait(" in src
        assert "timeout_ms=2000" in src

    def test_fragile_selector_gets_warning(self) -> None:
        src = emit_bot([_click(name="Report 12345", control_type="button")])
        assert "# WARNING:" in src
        assert "dynamic" in src

    def test_unknown_tool_raises(self) -> None:
        with pytest.raises(InvalidInput, match="Cannot emit code"):
            emit_bot([{"tool": "windows.nuke", "args": {}}])

    def test_generated_source_compiles(self) -> None:
        src = emit_bot(
            [
                _click(name="OK", control_type="button"),
                {"tool": "windows.input_text", "args": {"name": "Field"}},
                {"tool": "windows.wait", "args": {"timeout_ms": 500}},
            ]
        )
        compile(src, "bot.py", "exec")


class TestEmitFile:
    def test_roundtrip(self, tmp_path: Any) -> None:
        capture = tmp_path / "flow.json"
        out = tmp_path / "bot.py"
        capture.write_text(
            json.dumps(
                {"tool": "selector-capture", "nodes": [_click(name="OK")]},
            ),
            encoding="utf-8",
        )
        src = emit_file(str(capture), str(out))
        assert out.read_text(encoding="utf-8") == src
        assert "name='OK'" in src

    def test_missing_nodes_raises(self, tmp_path: Any) -> None:
        capture = tmp_path / "sel.json"
        capture.write_text(json.dumps({"tool": "selector-capture"}), encoding="utf-8")
        with pytest.raises(InvalidInput, match="no 'nodes'"):
            emit_file(str(capture), str(tmp_path / "bot.py"))


class TestEmitCli:
    def test_emit_dispatches(self, tmp_path: Any) -> None:
        from smithcore.windows.tools.selector_capture.cli import main

        src_in = str(tmp_path / "flow.json")
        dst = str(tmp_path / "bot.py")
        with patch(
            "smithcore.windows.tools.selector_capture.cli.emit_file",
            return_value="src",
        ) as emit:
            main(["emit", "-i", src_in, "-o", dst])
        emit.assert_called_once_with(src_in, dst)

    def test_series_emit_flag(self, tmp_path: Any) -> None:
        from smithcore.windows.tools.selector_capture.cli import main

        out = str(tmp_path / "rec.json")
        bot = str(tmp_path / "bot.py")
        with (
            patch("smithcore.windows.tools.selector_capture.cli.run_series_mode") as run,
            patch("smithcore.windows.tools.selector_capture.cli.emit_file") as emit,
        ):
            main(["series", "-o", out, "--emit", bot])
        run.assert_called_once_with(output=out)
        emit.assert_called_once_with(out, bot)

    def test_emit_skipped_when_no_emit_flag(self, tmp_path: Any) -> None:
        from smithcore.windows.tools.selector_capture.cli import main

        out = str(tmp_path / "rec.json")
        with (
            patch("smithcore.windows.tools.selector_capture.cli.run_series_mode") as run,
            patch("smithcore.windows.tools.selector_capture.cli.emit_file") as emit,
        ):
            main(["series", "-o", out])
        run.assert_called_once_with(output=out)
        emit.assert_not_called()
